### ISSUE TITLE
Avro data to Cassandra column

### ISSUE THREAD

**Issue by mradha1** [datastax/kafka-examples#6]
Hi ,
For example , if i am publishing the following records to kafka (Avro record)
**Key** = null
**Value** = {"first_name":"Sam", "last_name":"Mathew"}

**Below is my Cassandra table structure:**
CREATE TABLE mydevelopment.test_data
(
id text,
payload text,
PRIMARY KEY (id)
)

if I wanted to save  whole of the key value , {"first_name":"Sam", "last_name":"Mathew"} to the "payload" column in cassandra... what should be the below mapping value ???

{
  "name": "dse-connector-avro-example",
  "config": {
    "connector.class": "com.datastax.kafkaconnector.DseSinkConnector",
    "tasks.max": "10",
    "topics": "avro-stream",
    "contactPoints": "xx.xx.xx.xx",
    "loadBalancing.localDc": "Cassandra",
    "topic.avro-stream.kafka_examples.avro_udt_table.mapping": "?????????"
  }
}
Thanks !!!

**Comment by tomekl007** [comment]
Hi, 
What do you mean by insert to the `payload` column? Is this `payload` a UDT that has two fields: 
`first_name` and `last_name`?

**Comment by mradha1** [comment]
Hi,
The below is my requirement.

For example , if i am publishing the following records to kafka (Avro record)
Key = null
Value = {"id":"123", "first_name":"Mathew"}

Below is my Cassandra table structure:
CREATE TABLE kafka_examples.avro_udt_table
(
id text,
payload text,
PRIMARY KEY (id)
)

if I wanted to save whole of the Value , {"id":"123", "first_name":"Mathew"} to the "payload" column in cassandra... what should be the below mapping value ???

{
"name": "dse-connector-avro-example",
"config": {
"connector.class": "com.datastax.kafkaconnector.DseSinkConnector",
"tasks.max": "10",
"topics": "avro-stream",
"contactPoints": "xx.xx.xx.xx",
"loadBalancing.localDc": "Cassandra",
"topic.avro-stream.kafka_examples.avro_udt_table.mapping": "?????????"
}
}

Hope the requirement is clear.

Thanks !!!

**Comment by tomekl007** [comment]
To make it work you need to create a UDT in Cassandra that has `id` and `first_name`. Let's assume that you are creating this udt column and name it `payload`.
Once you have that, you can create this mapping:
`*.mapping = "payload=value"`
The whole value will be inserted into the payload column. For more details please see this example:
https://github.com/datastax/kafka-examples/tree/master/producers/src/main/java/json/udt
of saving value as a UDT in the Cassandra.

**Comment by mradha1** [comment]
Thanks for help..I am seeing the below exception
com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [TEXT <-> org.apache.kafka.connect.data.Struct]

**Comment by tomekl007** [comment]
When starting the connector, you need to have a proper `key.converter` and `value.converter` defined. If you have Json data in the Kafka topic you can base on this:
https://github.com/datastax/kafka-examples/blob/master/producers/src/main/java/json/connect-distributed-json.properties. If avro see this:
https://github.com/datastax/kafka-examples/blob/master/producers/src/main/java/avro/connect-distributed-avro.properties#L4
Please read this blogpost about setting converters:
https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained
